version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: PolyTerminal
      MYSQL_DATABASE: PolyTerminal
      MYSQL_USER: admin
      MYSQL_PASSWORD: PolyTerminal
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
